/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#004395",
        "inverse-primary": "#7331df",
        "on-primary-fixed-variant": "#5b00c5",
        "on-tertiary-fixed": "#2c0051",
        "on-surface-variant": "#ccc3d7",
        "on-tertiary-container": "#e3c2ff",
        "on-secondary-fixed": "#001a42",
        "inverse-on-surface": "#313031",
        "primary-container": "#6d28d9",
        "tertiary": "#ddb7ff",
        "error-container": "#93000a",
        "surface-tint": "#d3bbff",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#ddb7ff",
        "on-primary-fixed": "#250059",
        "surface-bright": "#3a393a",
        "tertiary-container": "#7d21cb",
        "on-surface": "#e5e2e3",
        "surface-dim": "#131314",
        "inverse-surface": "#e5e2e3",
        "primary": "#d3bbff",
        "surface": "#131314",
        "secondary": "#adc6ff",
        "on-background": "#e5e2e3",
        "outline": "#958da1",
        "surface-container-low": "#1c1b1c",
        "on-tertiary-fixed-variant": "#6900b3",
        "surface-container": "#201f20",
        "primary-fixed": "#ebddff",
        "on-secondary": "#002e6a",
        "on-primary-container": "#dac5ff",
        "secondary-fixed-dim": "#adc6ff",
        "surface-variant": "#353436",
        "primary-fixed-dim": "#d3bbff",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#353436",
        "secondary-container": "#0566d9",
        "tertiary-fixed": "#f0dbff",
        "outline-variant": "#4a4455",
        "on-tertiary": "#490080",
        "on-secondary-container": "#e6ecff",
        "background": "#131314",
        "surface-container-lowest": "#0e0e0f",
        "secondary-fixed": "#d8e2ff",
        "surface-container-high": "#2a2a2b",
        "error": "#ffb4ab",
        "on-primary": "#3f008d"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      }
    },
  },
  plugins: [],
}
